dist: xenial
language: go
go:
- 1.17.x

env:
  global:
  - DEBUG=true

before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}

script:
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
    --force-coverage-parser go -r coverage.cov
